# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-evaluate-code-4',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-evaluate-code-4',
                'lib_path': 'test_evaluate_code_4'},
  'syms': {'test_evaluate_code_4.core': {'test_evaluate_code_4.core.foo': ('core.html#foo', 'test_evaluate_code_4/core.py')}}}