name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
env:
  TEST_ENV_VAR: test_env_set_on_github
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Write Earth Engine credentials file
        run: |
          echo "DEBUG EGGPLANT"
          echo $TEST_ENV_VAR
          echo "DEBUG EGGPLANT"
      - uses: fastai/workflows/quarto-ghp@master
        with: {pre: 1}
